# Generated by Django 4.2.3 on 2024-10-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_propiedad', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('estacionamiento', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.condominio')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.residentes')),
            ],
        ),
    ]
