# Generated by Django 4.2.3 on 2024-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaestacionamiento',
            name='estado_estacionamiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
