# Generated by Django 4.2.3 on 2024-10-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentes',
            old_name='propiedad_id',
            new_name='propiedad',
        ),
    ]
