# Generated by Django 4.2.3 on 2024-10-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEstacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionEstacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_estacionamiento', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estadoestacionamiento')),
                ('tipo_estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipoestacionamiento')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ubicacionestacionamiento')),
            ],
        ),
    ]
