# Generated by Django 4.2.3 on 2024-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reservaestacionamiento_estado_estacionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaestacionamiento',
            name='residente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
