# Generated by Django 4.2.3 on 2024-10-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_propiedad_id_residentes_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentes',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
