# Generated by Django 4.2.3 on 2024-10-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_estadoestacionamiento_tipoestacionamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut_visita', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('relacion_residente', models.CharField(max_length=50)),
                ('patente_vehiculo', models.CharField(max_length=8)),
                ('descripcion_vehiculo', models.CharField(max_length=100)),
                ('tiempo_permanencia', models.TimeField()),
                ('fecha_registro_visita', models.DateTimeField(auto_now_add=True)),
                ('fecha_llegada_visita', models.DateTimeField()),
                ('fecha_modifica_reserva', models.DateTimeField(auto_now=True)),
                ('numero_est', models.IntegerField()),
                ('empleado', models.IntegerField()),
                ('estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estacionamiento')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.propiedad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipoestacionamiento')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ubicacionestacionamiento')),
            ],
        ),
    ]
