# Generated by Django 4.2.3 on 2024-11-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_residente_reservaestacionamiento_id_residente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaestacionamiento',
            old_name='id_residente',
            new_name='id_residente2',
        ),
    ]
