# Generated by Django 4.2.3 on 2024-10-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reservaestacionamiento_fecha_llegada_visita_confirmada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaestacionamiento',
            name='descripcion_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservaestacionamiento',
            name='patente_vehiculo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='reservaestacionamiento',
            name='tiempo_permanencia',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
