# Generated by Django 4.2.3 on 2024-10-18 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('home', '0004_reservaestacionamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_registro_observacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_residente', models.CharField(max_length=50)),
                ('numero_dpto', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.empleados')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.propiedad')),
            ],
        ),
    ]
