# Generated by Django 4.2.3 on 2024-11-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_id_residente_reservaestacionamiento_id_residente2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaestacionamiento',
            name='estado_estacionamiento',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
