# Generated by Django 4.2.3 on 2024-10-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_reservaestacionamiento_descripcion_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaestacionamiento',
            name='estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.estacionamiento'),
        ),
    ]
