# Generated by Django 4.2.3 on 2024-10-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_reservaestacionamiento_estacionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='numero_propiedad',
            field=models.IntegerField(unique=True),
        ),
    ]
