# Generated by Django 4.2.3 on 2024-11-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_reservaestacionamiento_estado_estacionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaestacionamiento',
            name='fecha_fin_visita',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
