# Generated by Django 4.2.3 on 2024-10-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_propiedad_numero_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroEstacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estacionamiento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='numero_estacionamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.numeroestacionamiento'),
        ),
    ]
