# Generated by Django 5.1.1 on 2024-09-26 22:21

import apps.authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240921_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[apps.authentication.validators.validate_rut]),
        ),
    ]
