# Generated by Django 5.1.1 on 2024-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_empleado_fecha_ingreso_alter_empleado_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
