# Generated by Django 5.1.1 on 2024-10-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_id_rol_id_empleado_id_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id_region',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.rol'),
        ),
    ]
