# Generated by Django 5.1.1 on 2024-10-05 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_empleado_id_region_alter_empleado_id_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=10)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.comuna')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.region')),
                ('id_rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.rol')),
            ],
        ),
    ]
