# Generated by Django 4.2.3 on 2024-10-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_empleados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
